// Bundles the action's TypeScript entrypoint into a single committed file.
//
// Output is ESM with an `.mjs` extension so Node treats it as a module
// regardless of any `package.json` that happens to sit above the checked-out
// action on the runner. `@actions/core` v3 and `@actions/http-client` v4 are
// both ESM-only, so an ESM bundle is also the zero-transform option.
import { build } from 'esbuild';

await build({
  entryPoints: ['src/index.ts'],
  outfile: 'dist/index.mjs',
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  minify: false,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    // Some transitive dependencies still call `require()` at runtime. esbuild's
    // ESM output replaces it with a stub that throws unless a real `require`
    // is already in scope, so put one there.
    js: [
      '// Generated by scripts/build.mjs — do not edit. Run `npm run build` after changing src.',
      "import { createRequire as __blocksCreateRequire } from 'node:module';",
      "import { fileURLToPath as __blocksFileURLToPath } from 'node:url';",
      "import { dirname as __blocksDirname } from 'node:path';",
      'const require = __blocksCreateRequire(import.meta.url);',
      'const __filename = __blocksFileURLToPath(import.meta.url);',
      'const __dirname = __blocksDirname(__filename);',
    ].join('\n'),
  },
});
